##############################################################################
##                 The Calculus of Inductive Constructions                  ##
##                                                                          ##
##                                Projet Coq                                ##
##                                                                          ##
##                     INRIA                        ENS-CNRS                ##
##              Rocquencourt                        Lyon                    ##
##                                                                          ##
##                                  Coq V7                                  ##
##                                                                          ##
##                                                                          ##
##############################################################################

# WARNING
#
# This Makefile has been automagically generated by coq_makefile
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB=`camlp4 -where`
COQSRC=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS=$(OCAMLLIBS) $(COQSRC)
OPT=
COQFLAGS=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC=$(COQBIN)coqc
GALLINA=gallina
COQDOC=coqdoc
CAMLC=ocamlc -c
CAMLOPTC=ocamlopt -c
CAMLLINK=ocamlc
CAMLOPTLINK=ocamlopt
COQDEP=$(COQBIN)coqdep -c
GRAMMARS=grammar.cma
CAMLP4EXTEND=pa_extend.cmo pa_ifdef.cmo q_MLast.cmo
PP=-pp "camlp4o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS=-I .\
  -I ../../Sophia-Antipolis/Algebra/\
  -I examples\
  -I extras\
  -I support\
  -I LinAlg
COQLIBS=-I .\
  -I ../../Sophia-Antipolis/Algebra/\
  -I examples\
  -I extras\
  -I support\
  -I LinAlg

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES=first_page.v\
  support/equal_syntax.v\
  support/more_syntax.v\
  LinAlg/vecspaces_verybasic.v\
  support/finite.v\
  examples/vecspace_Fn.v\
  support/Map2.v\
  examples/vecspace_functionspace.v\
  examples/Matrices.v\
  examples/vecspace_Mmn.v\
  LinAlg/alt_build_vecsp.v\
  examples/infinite_sequences.v\
  support/algebra_omissions.v\
  support/arb_intersections.v\
  LinAlg/subspaces.v\
  examples/antisymmetric_matrices.v\
  examples/symmetric_matrices.v\
  examples/up_lo_triang_mat.v\
  support/seq_set.v\
  support/seq_set_seq.v\
  support/empty.v\
  support/conshdtl.v\
  support/concat.v\
  support/const.v\
  support/omit.v\
  support/pointwise.v\
  support/modify_seq.v\
  support/mult_by_scalars.v\
  support/Map_embed.v\
  support/subseqs.v\
  support/sums.v\
  support/sums2.v\
  support/distinct.v\
  support/cast_seq_lengths.v\
  support/seq_equality.v\
  support/concat_facts.v\
  support/seq_equality_facts.v\
  support/distribution_lemmas.v\
  support/seq_set_facts.v\
  support/omit_facts.v\
  support/distinct_facts.v\
  support/cast_between_subsets.v\
  LinAlg/lin_combinations.v\
  LinAlg/spans.v\
  LinAlg/algebraic_span_facts.v\
  LinAlg/lin_comb_facts.v\
  LinAlg/direct_sum.v\
  LinAlg/lin_dependence.v\
  LinAlg/lin_dep_facts.v\
  support/random_facts.v\
  support/finite_subsets.v\
  support/has_n_elements.v\
  support/counting_elements.v\
  LinAlg/bases.v\
  LinAlg/bases_from_generating_sets.v\
  LinAlg/replacement_theorem.v\
  LinAlg/replacement_corollaries.v\
  LinAlg/bases_finite_dim.v\
  LinAlg/maxlinindepsubsets.v\
  LinAlg/subspace_dim.v\
  LinAlg/subspace_bases.v\
  LinAlg/Linear_Algebra_by_Friedberg_Insel_Spence.v\
  LinAlg/Lin_trafos.v\
  examples/trivial_spaces.v\
  examples/Matrix_multiplication.v\
  extras/ring_module.v\
  extras/Inter_intersection.v\
  extras/finite_misc.v\
  extras/restrict.v\
  extras/Matrix_related_defs.v\
  extras/before_after.v\
  extras/matrix_algebra.v\
  extras/Equality_structures.v
VOFILES=$(VFILES:.v=.vo)
VIFILES=$(VFILES:.v=.vi)
GFILES=$(VFILES:.v=.g)
HTMLFILES=$(VFILES:.v=.html)
GHTMLFILES=$(VFILES:.v=.g.html)

all: first_page.vo\
  support/equal_syntax.vo\
  support/more_syntax.vo\
  LinAlg/vecspaces_verybasic.vo\
  support/finite.vo\
  examples/vecspace_Fn.vo\
  support/Map2.vo\
  examples/vecspace_functionspace.vo\
  examples/Matrices.vo\
  examples/vecspace_Mmn.vo\
  LinAlg/alt_build_vecsp.vo\
  examples/infinite_sequences.vo\
  support/algebra_omissions.vo\
  support/arb_intersections.vo\
  LinAlg/subspaces.vo\
  examples/antisymmetric_matrices.vo\
  examples/symmetric_matrices.vo\
  examples/up_lo_triang_mat.vo\
  support/seq_set.vo\
  support/seq_set_seq.vo\
  support/empty.vo\
  support/conshdtl.vo\
  support/concat.vo\
  support/const.vo\
  support/omit.vo\
  support/pointwise.vo\
  support/modify_seq.vo\
  support/mult_by_scalars.vo\
  support/Map_embed.vo\
  support/subseqs.vo\
  support/sums.vo\
  support/sums2.vo\
  support/distinct.vo\
  support/cast_seq_lengths.vo\
  support/seq_equality.vo\
  support/concat_facts.vo\
  support/seq_equality_facts.vo\
  support/distribution_lemmas.vo\
  support/seq_set_facts.vo\
  support/omit_facts.vo\
  support/distinct_facts.vo\
  support/cast_between_subsets.vo\
  LinAlg/lin_combinations.vo\
  LinAlg/spans.vo\
  LinAlg/algebraic_span_facts.vo\
  LinAlg/lin_comb_facts.vo\
  LinAlg/direct_sum.vo\
  LinAlg/lin_dependence.vo\
  LinAlg/lin_dep_facts.vo\
  support/random_facts.vo\
  support/finite_subsets.vo\
  support/has_n_elements.vo\
  support/counting_elements.vo\
  LinAlg/bases.vo\
  LinAlg/bases_from_generating_sets.vo\
  LinAlg/replacement_theorem.vo\
  LinAlg/replacement_corollaries.vo\
  LinAlg/bases_finite_dim.vo\
  LinAlg/maxlinindepsubsets.vo\
  LinAlg/subspace_dim.vo\
  LinAlg/subspace_bases.vo\
  LinAlg/Linear_Algebra_by_Friedberg_Insel_Spence.vo\
  LinAlg/Lin_trafos.vo\
  examples/trivial_spaces.vo\
  examples/Matrix_multiplication.vo\
  extras/ring_module.vo\
  extras/Inter_intersection.vo\
  extras/finite_misc.vo\
  extras/restrict.vo\
  extras/Matrix_related_defs.vo\
  extras/before_after.vo\
  extras/matrix_algebra.vo\
  extras/Equality_structures.vo

spec: $(VIFILES)

gallina: $(GFILES)

html: $(HTMLFILES)

gallinahtml: $(GHTMLFILES)

all.ps: $(VFILES)
	$(COQDOC) -ps -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -ps -g -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

.SUFFIXES: .v .vo .vi .g .html .tex .g.tex .g.html

.v.vo:
	$(COQC) $(COQDEBUG) $(COQFLAGS) $*

.v.vi:
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

.v.g:
	$(GALLINA) $<

.v.tex:
	$(COQDOC) -latex $< -o $@

.v.html:
	$(COQDOC) -html $< -o $@

.v.g.tex:
	$(COQDOC) -latex -g $< -o $@

.v.g.html:
	$(COQDOC) -html -g $< -o $@

byte:
	$(MAKE) all "OPT="

opt:
	$(MAKE) all "OPT=-opt"

include .depend

.depend depend:
	rm -f .depend
	$(COQDEP) -i $(COQLIBS) *.v *.ml *.mli >.depend
	$(COQDEP) $(COQLIBS) -suffix .html *.v >>.depend

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f *.vo `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o *.vo *.vi *.g *~
	rm -f all.ps all-gal.ps $(HTMLFILES) $(GHTMLFILES)

archclean:
	rm -f *.cmx *.o

html:

# WARNING
#
# This Makefile has been automagically generated by coq_makefile
# Edit at your own risks !
#
# END OF WARNING

